---
title: "Psikometrik Ağ Analizi (Psychometric Network Analysis)"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library("eRm")
library("dplyr")
library("psychonetrics")
library("qgraph")
library("mirt")
```

## Gerekli Paketler

* **R version:** R-4.4.2 for Windows (<https://cran.r-project.org/>)
* **Rtools version:** Rtools44 for Windows (<https://cran.r-project.org/bin/windows/Rtools/rtools44/rtools.html>)
* **RStudio version:** RStudio 2024.12.0+467
* EGAnet paketine dair ek bilgiler: <https://r-ega.net/>

```{r ch1, eval=FALSE}
install.packages(c("eRm", "dplyr", "psychonetrics", "qgraph", "mirt"))
# install.packages(c("parallelly", "testthat"))

library("eRm")
library("dplyr")
library("psychonetrics")
library("qgraph")
library("mirt")
```

```{r ch2}
#simulating Rasch homogenous data
# 1000 persons, 30 items, parameter drawn from N(0,1)
data <- sim.rasch(1000, 10)

data <- as.data.frame(data)
colnames(data) <- paste0("i", 1:10)

vars <- names(data)

# Form saturated model:
model1 <- Ising(data, vars = vars)

# Run model:
model1 <- model1 %>% runmodel

# Prune-stepup to find a sparse model: 
model1b <- model1 %>% prune(alpha = 0.05) %>% stepup(alpha = 0.05)

# Compare all models:
comparison <- compare(
  `1. all parameters free (dense)`  = model1,
  `2. all parameters free (sparse)` = model1b)

# Print results:
print(comparison)

# Make labels:
labels <- paste0("item", 1:10)

# Extract network structure and thresholds:
network <- getmatrix(model1b, "omega")
thresholds <- getmatrix(model1b, "tau")

# Scale thresholds for colors:
scaledthresh <- as.vector(thresholds / (2*max(abs(thresholds))))

# Make colors:
cols <- ifelse(scaledthresh < 0, "red", "darkblue")
cols[scaledthresh>0] <- qgraph:::Fade(cols[scaledthresh>0],alpha = scaledthresh[scaledthresh>0], "white")
cols[scaledthresh<0] <- qgraph:::Fade(cols[scaledthresh<0],alpha = abs(scaledthresh)[scaledthresh<0], "white")

# Plot network:
qgraph(network, layout = "spring", labels = labels,
       shape = "rectangle", vsize = 15, vsize2 = 8,
       theme = "colorblind", color = cols,
       cut = 0.5, repulsion = 0.9)
```


```{r ch3}
# Testlet response model
library("mirt")

# Simulate data
set.seed(2021)
a <- matrix(0, 12, 4)
a[,1] <- rlnorm(12, .2, .3)

ind <- 1
for(i in 1:3){
  a[ind:(ind+3),i+1] <- a[ind:(ind+3),1]
  ind <- ind+4
}

print(a)

d <- rnorm(12, 0, .5)
sigma <- diag(c(1, .5, 1, .5))
dataset <- simdata(a, d, 2000, itemtype=rep('2PL', 12), sigma=sigma)

dataset <- as.data.frame(dataset)
vars <- names(dataset)

# Form saturated model:
model1 <- Ising(dataset, vars = vars)

# Run model:
model1 <- model1 %>% runmodel

# Prune-stepup to find a sparse model: 
model1b <- model1 %>% prune(alpha = 0.05) %>% stepup(alpha = 0.05)

# Compare all models:
comparison <- compare(
  `1. all parameters free (dense)`  = model1,
  `2. all parameters free (sparse)` = model1b)

# Print results:
print(comparison)

# Make labels:
labels <- paste0("Item_", 1:12)

# Extract network structure and thresholds:
network <- getmatrix(model1b, "omega")
thresholds <- getmatrix(model1b, "tau")

# Scale thresholds for colors:
scaledthresh <- as.vector(thresholds / (2*max(abs(thresholds))))

# Make colors:
cols <- ifelse(scaledthresh < 0, "red", "darkblue")
cols[scaledthresh>0] <- qgraph:::Fade(cols[scaledthresh>0],alpha = scaledthresh[scaledthresh>0], "white")
cols[scaledthresh<0] <- qgraph:::Fade(cols[scaledthresh<0],alpha = abs(scaledthresh)[scaledthresh<0], "white")

# Plot network:
qgraph(network, layout = "spring", labels = labels,
       shape = "rectangle", vsize = 15, vsize2 = 8,
       theme = "colorblind", color = cols,
       cut = 0.5, repulsion = 0.9)
```
